import type { LlmProvider } from '@core/agents/LlmProvider';
import type { TestPlan } from './types';

const SYSTEM_PROMPT =
  'You write TypeScript page objects for a Playwright framework. Page objects extend BasePage ' +
  "from '@core/pages/BasePage' and declare elements via this.elements.button/input/dropdown/" +
  'checkbox/link/text({ selector, description }). Reply with strict JSON only, no prose.';

/** Second pipeline stage: turns a `TestPlan` into the page-object source file. */
export class PageObjectAgent {
  constructor(private readonly provider: LlmProvider) {}

  async write(plan: TestPlan): Promise<string> {
    const raw = await this.provider.complete([
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: this.buildPrompt(plan) },
    ]);
    return this.parse(raw, plan);
  }

  private buildPrompt(plan: TestPlan): string {
    return [
      'TASK: write-page-object',
      `Page object class name: ${plan.pageObjectName}`,
      `Scenario: "${plan.title}"`,
      `Steps the page object should support: ${JSON.stringify(plan.steps)}`,
      'Reply with strict JSON: {"content": "<the full .ts file content as a string>"}.',
    ].join('\n\n');
  }

  private parse(raw: string, plan: TestPlan): string {
    try {
      const parsed = JSON.parse(raw) as { content?: string };
      if (!parsed.content || !parsed.content.includes(plan.pageObjectName)) {
        throw new Error('missing or unusable content');
      }
      return parsed.content;
    } catch {
      return this.fallback(plan);
    }
  }

  private fallback(plan: TestPlan): string {
    return [
      "import { BasePage } from '@core/pages/BasePage';",
      '',
      '/**',
      ` * Generated by PageObjectAgent for: "${plan.title}"`,
      ' * This is an offline skeleton (no live LLM was used) — fill in real selectors and',
      ' * descriptions before running the matching spec.',
      ' */',
      `export class ${plan.pageObjectName} extends BasePage {`,
      ...plan.steps.map(
        (step, index) =>
          `  // TODO element for step ${index + 1} ("${step}"): this.elements.button({ selector: 'CHANGE_ME', description: 'CHANGE_ME' });`,
      ),
      '}',
      '',
    ].join('\n');
  }
}
