import type { LlmProvider } from '@core/agents/LlmProvider';
import type { TestPlan } from './types';

const SYSTEM_PROMPT =
  "You write Playwright spec files for this framework. Import `test`/`expect` from " +
  "'@core/fixtures/test' and the page object from the given import path, use " +
  '`pages.create(PageObjectClass)` to instantiate it. Reply with strict JSON only, no prose.';

/** Third pipeline stage: turns a `TestPlan` + the page object's import path into a spec file. */
export class WriterAgent {
  constructor(private readonly provider: LlmProvider) {}

  async write(plan: TestPlan, pageObjectImportPath: string): Promise<string> {
    const raw = await this.provider.complete([
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: this.buildPrompt(plan, pageObjectImportPath) },
    ]);
    return this.parse(raw, plan, pageObjectImportPath);
  }

  private buildPrompt(plan: TestPlan, pageObjectImportPath: string): string {
    return [
      'TASK: write-spec',
      `Page object import path: "${pageObjectImportPath}"`,
      `Page object class name: ${plan.pageObjectName}`,
      `Scenario: "${plan.title}"`,
      `Steps: ${JSON.stringify(plan.steps)}`,
      `Assertions: ${JSON.stringify(plan.assertions)}`,
      'Reply with strict JSON: {"content": "<the full .spec.ts file content as a string>"}.',
    ].join('\n\n');
  }

  private parse(raw: string, plan: TestPlan, pageObjectImportPath: string): string {
    try {
      const parsed = JSON.parse(raw) as { content?: string };
      if (!parsed.content || !parsed.content.includes(plan.pageObjectName)) {
        throw new Error('missing or unusable content');
      }
      return parsed.content;
    } catch {
      return this.fallback(plan, pageObjectImportPath);
    }
  }

  private fallback(plan: TestPlan, pageObjectImportPath: string): string {
    const stepComments = plan.steps.map((step) => `    // ${step}`).join('\n');
    const assertionComments = plan.assertions.map((assertion) => `    // TODO assert: ${assertion}`).join('\n');
    return [
      "import { test, expect } from '@core/fixtures/test';",
      `import { ${plan.pageObjectName} } from '${pageObjectImportPath}';`,
      '',
      `// Generated by WriterAgent for: "${plan.title}"`,
      '// This is an offline skeleton (no live LLM was used) — flesh out the steps below.',
      `test.describe('${plan.title}', () => {`,
      `  test('${plan.title}', async ({ pages }) => {`,
      `    const page = pages.create(${plan.pageObjectName});`,
      '    void page;',
      '    void expect;',
      stepComments,
      assertionComments,
      '  });',
      '});',
      '',
    ].join('\n');
  }
}
